services:
  app:
    build: .
    image: laravel-app-gestao-escolar
    container_name: laravel-app-gestao-escolar
    volumes:
      - .:/var/www
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - laravel_gestao-escolar

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx-gestao-escolar
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_gestao-escolar

  queue-worker:
    image: laravel-app-gestao-escolar
    container_name: laravel-queue-worker-gestao-escolar
    volumes:
      - .:/var/www
    command: php artisan queue:work redis --sleep=3 --tries=3
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - laravel_gestao-escolar

  redis:
    image: redis:7-alpine
    container_name: laravel-redis-gestao-escolar  # Adicionado
    volumes:
      - redis_data:/data
    networks:  # ADICIONADO
      - laravel_gestao-escolar

  db:
    image: mysql:8.0
    container_name: laravel-db-gestao-escolar  # Adicionado
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestao-escolar
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot"]
      interval: 5s
      retries: 20
    networks:  # ADICIONADO
      - laravel_gestao-escolar

volumes:
  db_data:
  redis_data:

networks:
  laravel_gestao-escolar:
    driver: bridge